### ISSUE TITLE
JSON contains

### ISSUE THREAD

**Issue by aclowkey** [go-gorm/datatypes#4]
## Describe the feature

It would be nice to have an abillity to filter by the values of the json, and not just check their key presence

Something like
```go
datatypes.JSONContains("json_column").Path("$.labels.my_label").Value("my_value")
```
Which would be SQL in MySQL
```sql
SELECT * FROM my_table WHERE JSON_CONTAINS("json_column", '"my_value',  "$.labels.my_label")
```

Not sure how it would be in Postgres

## Motivation

As we might want to give users ability to filter based on specific json values from a set of attributes

**Comment by jinzhu** [comment]
```go
// Check JSON extract value from keys equal to value
datatypes.JSONQuery("attributes").Equals(value, keys...)

DB.First(&user, datatypes.JSONQuery("attributes").Equals("jinzhu", "name"))
DB.First(&user, datatypes.JSONQuery("attributes").Equals("orgb", "orgs", "orgb"))
```
