### ISSUE TITLE
Support Sqlite

### ISSUE THREAD

**Issue by mitar** [go-gorm/datatypes#6]
## Describe the feature

Please support also Sqlite. There is standard [extension](https://www.sqlite.org/json1.html) to support JSON.

## Motivation

We use Sqlite for unit tests, so it would be great if this could work there as well.

**Comment by mitar** [comment]
Awesome. Thanks.

**Comment by aveyuan** [comment]
Hi, I use sqlite error.`no such function: JSON_EXTRACT`  is this supportd?
