### ISSUE TITLE
time type support

### ISSUE THREAD

**Issue by masaushi** [go-gorm/datatypes#88]
## Describe the feature

It would be nice to have a custom data type for database clock time type like `hh:mm:ss` format.

Many databases such as MySQL, PostgreSQL and SQLServer have `Time` column type, so it is useful to have support for `time` type in many use cases.

## Motivation

It takes some time and effort to handle database time.

If we use `time.Time` for handling database time, we will get the following error:
`unsupported Scan, storing driver.Value type []uint8 into type *time.Time`

Therefore, developers have to define their own type for database time type.

**Comment by jinzhu** [comment]
https://github.com/go-gorm/datatypes/blob/master/time.go
